### ISSUE TITLE
Installing Kubernetes CRD fails in k8s 1.18.8

### ISSUE THREAD

**Issue by amuraru** [pravega/zookeeper-operator#254]
### Description

Trying to install the ZK CRD
```
kubectl apply -f https://raw.githubusercontent.com/pravega/zookeeper-operator/master/deploy/crds/zookeeper.pravega.io_zookeeperclusters_crd.yaml
```
fails with
```
The CustomResourceDefinition "zookeeperclusters.zookeeper.pravega.io" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
```

**Comment by Prabhaker24** [comment]
@amuraru  what is the yaml file you are using for deploying the zookeeper cluster?

**Comment by amuraru** [comment]
hi @SrishT - this hasn't anything to do with ZK cluster creation IMO. it's failing in the very beginning when I try to install the `crd` in my cluster.

Simple steps to reproduce:
```
curl -Lo ./kind "https://github.com/kubernetes-sigs/kind/releases/download/v0.9.0/kind-$(uname)-amd64"
chmod +x ./kind
mv ./kind ~/bin


mkdir ~/.kind
cat > ~/.kind/kind-config.yaml <<EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
EOF

kind create cluster \
--name zk \
--config ~/.kind/kind-config.yaml \
--image kindest/node:v1.18.8

kubectl apply -f https://raw.githubusercontent.com/pravega/zookeeper-operator/master/deploy/crds/zookeeper.pravega.io_zookeeperclusters_crd.yaml


```

**Comment by amuraru** [comment]
related issues in other operators:

- datastax/cass-operator#132
- kubernetes-sigs/controller-tools#444
- operator-framework/operator-sdk#3235

**Comment by anishakj** [comment]
Fixed by PR https://github.com/pravega/zookeeper-operator/pull/255

**Comment by diranged** [comment]
@anishakj This is not actually fixed. The helm charts still include this `protocol` key in the list of required parameters, but the file at https://raw.githubusercontent.com/pravega/zookeeper-operator/v0.2.9/deploy/crds/zookeeper.pravega.io_zookeeperclusters_crd.yaml does not. The https://raw.githubusercontent.com/pravega/zookeeper-operator/v0.2.9/deploy/crds/zookeeper.pravega.io_zookeeperclusters_crd.yaml file works fine, but the helm charts fail exactly as the original author noted.

**Comment by anishakj** [comment]
We have added the check here in helm charts. https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper-operator/templates/zookeeper.pravega.io_zookeeperclusters_crd.yaml#L692

**Comment by diranged** [comment]
> We have added the check here in helm charts. https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper-operator/templates/zookeeper.pravega.io_zookeeperclusters_crd.yaml#L692

So I am not familiar with how that semvar compare function works - but on our 1.18.8 EKS cluster, it was comparing to "true" and inserting the protocol line. Is it possible that the check is somehow backwards? Here's our server version line:

```
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by amuraru** [comment]
@diranged are you using `helm template ... | kubectl apply -f" or `helm install ...` for the helm chart?
In the former case the actual server side version is not taken into consideration and helm is using the version it was built against: https://github.com/helm/helm/issues/7991#issuecomment-620223572

IMO: we should remove that check altogether from the helm chart crd tempalte

**Comment by diranged** [comment]
@amuraru Oh - I didn't know that's how it worked.. that is actually a silly behavior. I agree that this check should go away because that is not how most people are going to use helm. In our case we're using helm through argocd.
